s:
	gcc server.c stringMisc.c packet.c packetQueue.c packetBuffer.c parsePacket.c client.c channel.c queue.c parseInputServer.c -o pS
c:
	gcc clientProgram.c stringMisc.c packet.c packetQueue.c packetBuffer.c parsePacket.c parseInputClient.c -o pC
